bot:
    token: 1715242540:AAE9FZMUHx8UnJ_luf8Wm9o0sITwHvpJwws
    parse_mode: html

executor:
    skip_updates: true

modules:
    - handlers.main
    - handlers.errors

log_ignore:
    - aiogram
    - asyncio
    - aiogram.Middleware

commands:
    start: Начать беседу со мной
